### ISSUE TITLE
BUG: Enemies sometimes don't fully smash

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#1001]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

All

### Issue Description

Enemies sometimes don't smash when they should take lethal damage.  This issue is really several other issues that we're lumping into 1 since they are all related to race conditions.  

This issue will never be fully solved, just mitigated as the server becomes more robust.

### Reproduction Steps

Deal what would be lethal damage to an enemy at the same frame you take damage from them on the server
Enemy respawns after 4 seconds

### Expected Behavior

Enemy dies as expected

### Environment

All

**Comment by EmosewaMC** [comment]
I believe I have found the answer and solution to this issue.  More details when I wrap up some current PRs.
Here is the dump of my research and thoughts on how to handle this:

I was thinking about how a player with a lot of latency would even enjoy the game in this state and then it hit me that we need to do the syncs on our end and when a client requests a sync we simply verify what we already have calculated on the server and if it matches ship it to the client
So we simulate the full skill to completion and simply network the syncs that are requested by the client after we verify their integrity
Skill delay timings right now are the following:
Network latency + delay until packet processed + actual Skill sync time

**Comment by MustacheMan2** [comment]
this doesn't really seem fixed at all lol

**Comment by EmosewaMC** [comment]
> this doesn't really seem fixed at all lol

#1045

**Comment by EmosewaMC** [comment]
can I also just say, thank you for the update to a bug.  I have noted your descriptive report and will use it do deduce where issues still are happening.

**Comment by MustacheMan2** [comment]
I take back what I said earlier. Sorry for any confusion or frustration I caused.

**Comment by EmosewaMC** [comment]
To be fair there was a copy paste error I was unaware of which broke more than I fixed.  I would have caught it if any other compiler warned me that converting from a decimal number to a true false statement is a red flag
