### ISSUE TITLE
Random Disconnects

### ISSUE THREAD

**Issue by IAmVolvic** [DarkflameUniverse/DarkflameServer#105]
Fatal error 11
Stacktrace:
./WorldServer(+0xe4b2f)[0x5622a5d12b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7fee3321f3c0]
/lib/x86_64-linux-gnu/libc.so.6(+0x16e052)[0x7fee32e31052]
./WorldServer(+0x1cb8d3)[0x5622a5df98d3]
./WorldServer(+0x1be36c)[0x5622a5dec36c]
./WorldServer(+0x1cffbe)[0x5622a5dfdfbe]
./WorldServer(+0xcd3db)[0x5622a5cfb3db]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fee32cea0b3]
./WorldServer(+0xdc29e)[0x5622a5d0a29e]
double free or corruption (out)

Fatal error 6
Stacktrace:
./WorldServer(+0xe4b2f)[0x5622a5d12b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7fee3321f3c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fee32d0918b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7fee32ce8859]
/lib/x86_64-linux-gnu/libc.so.6(+0x903ee)[0x7fee32d533ee]
/lib/x86_64-linux-gnu/libc.so.6(+0x9847c)[0x7fee32d5b47c]
/lib/x86_64-linux-gnu/libc.so.6(+0x9a120)[0x7fee32d5d120]
/home/adminpie/Desktop/LegoU/DarkflameServerTest/DarkflameServer/build/_deps/mysql-src/lib64/libmysqlcppconn.so.9(_ZNSs7reserveEm+0x89)[0x7fee33374209]
/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendERKSs+0x3b)[0x7fee330f542b]
./WorldServer(+0xe4bb9)[0x5622a5d12bb9]

Fatal error 11
Stacktrace:
./WorldServer(+0xe4b2f)[0x5622a5d12b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7fee3321f3c0]
./WorldServer(+0x405340)[0x5622a6033340]
./WorldServer(+0x406a00)[0x5622a6034a00]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7fee33213609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7fee32de5293]
[07-12-21 17:26:31] [BehaviorContext]: Failed to find behavior sync entry with sync id (283)!

[07-12-21 17:35:39] [ActivityManager]: Executing timer 'PlaySpawnSound'
Fatal error 11
Stacktrace:
./WorldServer(+0xe4b2f)[0x55bdfb4d2b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f42fa1723c0]
/lib/x86_64-linux-gnu/libc.so.6(+0x16e048)[0x7f42f9d84048]
./WorldServer(+0x1cb8d3)[0x55bdfb5b98d3]
./WorldServer(+0x1be36c)[0x55bdfb5ac36c]
./WorldServer(+0x1cffbe)[0x55bdfb5bdfbe]
./WorldServer(+0xcd3db)[0x55bdfb4bb3db]
/lib/x86_64-linux-gnu/libc.so.6(libc_start_main+0xf3)[0x7f42f9c3d0b3]
./WorldServer(+0xdc29e)[0x55bdfb4ca29e]
malloc(): corrupted top size

Fatal error 6
Stacktrace:
./WorldServer(+0xe4b2f)[0x55bdfb4d2b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f42fa1723c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f42f9c5c18b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f42f9c3b859]
/lib/x86_64-linux-gnu/libc.so.6(+0x903ee)[0x7f42f9ca63ee]
/lib/x86_64-linux-gnu/libc.so.6(+0x9847c)[0x7f42f9cae47c]
/lib/x86_64-linux-gnu/libc.so.6(+0x9b83a)[0x7f42f9cb183a]
/lib/x86_64-linux-gnu/libc.so.6(libc_malloc+0x1b9)[0x7f42f9cb3419]
/lib/x86_64-linux-gnu/libc.so.6(_IO_file_doallocate+0x94)[0x7f42f9c9ae84]
/lib/x86_64-linux-gnu/libc.so.6(_IO_doallocbuf+0x50)[0x7f42f9cab050]
munmap_chunk(): invalid pointer
Fatal error 6
Stacktrace:
./WorldServer(+0xe4b2f)[0x55bdfb4d2b2f]

**Comment by IAmVolvic** [comment]
Server: Ubuntu

**Comment by badooga** [comment]
Am also having this issue, it's causing the server I'm playing on to crash like every few minutes with seemingly no cause. Except, it only seems to occur in Avant Gardens. Super confusing and annoying.

**Comment by enteryournamehere** [comment]
I'm getting the same on Ubuntu (20.04.3 LTS). World server crashes every couple minutes (only tested much with AG so far). Sometimes it's up for longer, sometimes it's less than a minute. I haven't been able to link it to any in-game action so far. AG Survival usually crashes a few seconds in.

**Comment by IAmVolvic** [comment]
> 

Same goes for my " Friends " who also play on my server..

**Comment by Jettford** [comment]
Same issue on Ubuntu Server 20 when doing things though, I don't get disconnected unless I interact with something and there appears to be no pattern.

**Comment by enteryournamehere** [comment]
Everything appears to work without issues on commit 73ef2e6

**Comment by Pr3roxDLC** [comment]
Can once again confirm the same happening to me on Ubuntu 18.04

**Comment by Pr3roxDLC** [comment]
@enteryournamehere im also getting this crash: `Fatal error 11
Stacktrace:
./WorldServer(+0x7f33b)[0x5653e102a33b]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f1aabe79980]
/lib/x86_64-linux-gnu/libc.so.6(+0x18ecf1)[0x7f1aab0bccf1]
./WorldServer(+0x16b47b)[0x5653e111647b]
./WorldServer(+0x160a3b)[0x5653e110ba3b]
./WorldServer(+0x17018f)[0x5653e111b18f]
./WorldServer(+0x67efe)[0x5653e1012efe]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f1aaaf4fbf7]
./WorldServer(+0x758ea)[0x5653e10208ea]
` but i think i can link it to gameplay, everything works perfectly fine as long as no players are in reach of any enemies in AG, so if all players are inside the Sentinels Camp, Monument Area or the Launch Place everything will work fine, only if someone steps outside of these areas the crash accurs for me

**Comment by CoalSephos** [comment]
> I'm getting the same on Ubuntu (20.04.3 LTS). World server crashes every couple minutes (only tested much with AG so far). Sometimes it's up for longer, sometimes it's less than a minute. I haven't been able to link it to any in-game action so far. AG Survival usually crashes a few seconds in.

Currently experiencing the same issue on Ubuntu 20.04.3 LTS.

**Comment by JoachimFlottorp** [comment]
[08-12-21 01:35:13] [SpiderQueen]: hatching egg 288300748454049585
Fatal error 11
Stacktrace:
./WorldServer(+0xe4b2f)[0x7fac15dcbb2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7fac1524a3c0]
/lib/x86_64-linux-gnu/libc.so.6(+0x187ec8)[0x7fac14e47ec8]
./WorldServer(+0x1be315)[0x7fac15ea5315]
./WorldServer(+0x1cffbe)[0x7fac15eb6fbe]
./WorldServer(+0xcd3db)[0x7fac15db43db]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fac14ce70b3]
./WorldServer(+0xdc29e)[0x7fac15dc329e]

During the boss fight once first time entering the build plot

OS: Host windows 10: WSL Ubuntu 20.04

**Comment by averysumner** [comment]
Can you guys please test this again now that #83 has been reverted?

**Comment by DannyBoy107** [comment]
Can confirm, still happening;

Fatal error 11
Stacktrace:
./WorldServer(+0xe4b2f)[0x55ded51f4b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f6b0d3323c0]
/lib/x86_64-linux-gnu/libc.so.6(+0x18e959)[0x7f6b0cf64959]
./WorldServer(+0x1cb8d3)[0x55ded52db8d3]
./WorldServer(+0x1be36c)[0x55ded52ce36c]
./WorldServer(+0x1cffbe)[0x55ded52dffbe]
./WorldServer(+0xcd3db)[0x55ded51dd3db]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f6b0cdfd0b3]
./WorldServer(+0xdc29e)[0x55ded51ec29e]
double free or corruption (out)
Fatal error 6
Stacktrace:
./WorldServer(+0xe4b2f)[0x55ded51f4b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f6b0d3323c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f6b0ce1c18b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f6b0cdfb859]
/lib/x86_64-linux-gnu/libc.so.6(+0x903ee)[0x7f6b0ce663ee]
/lib/x86_64-linux-gnu/libc.so.6(+0x9847c)[0x7f6b0ce6e47c]
/lib/x86_64-linux-gnu/libc.so.6(+0x9a120)[0x7f6b0ce70120]
./WorldServer(+0xe4d60)[0x55ded51f4d60]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f6b0d3323c0]
/lib/x86_64-linux-gnu/libc.so.6(+0x18e959)[0x7f6b0cf64959]
Fatal error 11
Stacktrace:
./WorldServer(+0xe4b2f)[0x55ded51f4b2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f6b0d3323c0]
./WorldServer(+0x405340)[0x55ded5515340]
./WorldServer(+0x406a00)[0x55ded5516a00]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7f6b0d326609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f6b0cef8293]

**Comment by NovaEB** [comment]
Just got the game working, still happening on my end. Is happening consistently whenever I try and go do the Advent Gardens Armor Polish quest. 

Fatal error 11
Stacktrace:
./WorldServer(+0xe4b2f)[0x555af516fb2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7ff5908ad3c0]
/lib/x86_64-linux-gnu/libc.so.6(+0x16e05c)[0x7ff5904ae05c]
./WorldServer(+0x1cb8d3)[0x555af52568d3]
./WorldServer(+0x1be36c)[0x555af524936c]
./WorldServer(+0x1cffbe)[0x555af525afbe]
./WorldServer(+0xcd3db)[0x555af51583db]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7ff5903670b3]
./WorldServer(+0xdc29e)[0x555af516729e]
double free or corruption (out)
Fatal error 6
Stacktrace:
./WorldServer(+0xe4b2f)[0x555af516fb2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7ff5908ad3c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7ff59038618b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7ff590365859]
/lib/x86_64-linux-gnu/libc.so.6(+0x903ee)[0x7ff5903d03ee]
/lib/x86_64-linux-gnu/libc.so.6(+0x9847c)[0x7ff5903d847c]
/lib/x86_64-linux-gnu/libc.so.6(+0x9a120)[0x7ff5903da120]
/DarkflameServer/build/_deps/mysql-src/lib64/libmysqlcppconn.so.9(_ZNSs7reserveEm+0x89)[0x7ff590a08209]
/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendERKSs+0x3b)[0x7ff59077742b]
./WorldServer(+0xe4c26)[0x555af516fc26]

**Comment by averysumner** [comment]
You guys did rebuild the server, right?

**Comment by IAmVolvic** [comment]
> You guys did rebuild the server, right?

I'll try it out. ( Ill edit this if anything happens )

**Comment by MickVermeulen** [comment]
I highly doubt that #83 caused this issue as it should only affect VE. I'm suspecting 7bead89e39226d8e43bb3951377406a588e7cd09 is causing the issue, it's deleting items from a list while looping through it.

**Comment by Jettford** [comment]
This is fixed now.

**Comment by CoalSephos** [comment]
No longer experiencing this issue after rebuilding!

**Comment by Pr3roxDLC** [comment]
Possibly unreleated but im still getting seamingly random crashes after rebuilding the client. `./WorldServer(+0x7ee3b)[0x558a37879e3b]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92ae6)[0x7fa7a7d86ae6]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92b21)[0x7fa7a7d86b21]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d54)[0x7fa7a7d86d54]
/root/DarkflameServer/build/_deps/mysql-src/lib64/libmysqlcppconn.so.9(+0x73a7b)[0x7fa7a8730a7b]
./WorldServer(+0x9ed7b)[0x558a37899d7b]
./WorldServer(+0x32faf6)[0x558a37b2aaf6]
./WorldServer(+0x352b91)[0x558a37b4db91]
./WorldServer(+0x37d2e3)[0x558a37b782e3]
./WorldServer(+0x15cb1e)[0x558a37957b1e]
Error: signal -1:
`

**Comment by MickVermeulen** [comment]
Closing as people are reporting this is no longer an issue, likely due to the troubling commit being reverted. Can always reopen.

**Comment by magokstad** [comment]
Hi, i'm getting "Error: signal 11" on the latest build.
I'm currently running the server on Ubuntu 22.04

Everything works fine until i enter Avant Gardens. The game runs fine for a couple of minutes, then i get the error.
I've also tried rebuilding, and even redoing the entire process on a new VM, still i get the same error.

This is the crash report i get in my crashlogs/world/ folder. It's the same every time.

```
./WorldServer(+0xab45a)[0x55ab6b64a45a]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f41aad07520]
./WorldServer(+0x191c3c)[0x55ab6b730c3c]
./WorldServer(+0x193874)[0x55ab6b732874]
./WorldServer(+0x193c2d)[0x55ab6b732c2d]
./WorldServer(+0x1a742a)[0x55ab6b74642a]
./WorldServer(+0x92b6c)[0x55ab6b631b6c]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f41aaceed90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f41aaceee40]
./WorldServer(+0xa1555)[0x55ab6b640555]
Error: signal 11:
```

Am i using the wrong Ubuntu version?
Is GCC version 11.2.0 ok?

If you need more information, i will happily provide it.

**Comment by magokstad** [comment]
> Hi, i'm getting "Error: signal 11" on the latest build. I'm currently running the server on Ubuntu 22.04
> 
> Everything works fine until i enter Avant Gardens. The game runs fine for a couple of minutes, then i get the error. I've also tried rebuilding, and even redoing the entire process on a new VM, still i get the same error.
> 
> This is the crash report i get in my crashlogs/world/ folder. It's the same every time.
> 
> ```
> ./WorldServer(+0xab45a)[0x55ab6b64a45a]
> /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f41aad07520]
> ./WorldServer(+0x191c3c)[0x55ab6b730c3c]
> ./WorldServer(+0x193874)[0x55ab6b732874]
> ./WorldServer(+0x193c2d)[0x55ab6b732c2d]
> ./WorldServer(+0x1a742a)[0x55ab6b74642a]
> ./WorldServer(+0x92b6c)[0x55ab6b631b6c]
> /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f41aaceed90]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f41aaceee40]
> ./WorldServer(+0xa1555)[0x55ab6b640555]
> Error: signal 11:
> ```
> 
> Am i using the wrong Ubuntu version? Is GCC version 11.2.0 ok?
> 
> If you need more information, i will happily provide it.

As a desperate last try, i tried building using an earlier commit from around April or may. That "fixed" the bug as i no longer get the error. I've play through to Nexus Tower now with no problems with a friend. I don't know if it was something I did, or if something was changed between April and now causing the error.

**Comment by EmosewaMC** [comment]
> As a desperate last try, i tried building using an earlier commit from around April or may. That "fixed" the bug as i no longer get the error. I've play through to Nexus Tower now with no problems with a friend. I don't know if it was something I did, or if something was changed between April and now causing the error.

Likely an issue you yourself have caused.  Several other users including myself are able to load into and play Avant Gardens just fine.  Please make sure you are using the lcdrs unpacked client and have followed the steps in the README as they are written and ensure you have run all the migrations.  Odds are you going to an earlier build undid something wrong you did and building from scratch again will result in a working server.
