### ISSUE TITLE
BUG: Frakjaw Battle minigame crashes

### ISSUE THREAD

**Issue by piersonjon** [DarkflameUniverse/DarkflameServer#265]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

During the Ninjago Monastery minigame Frakjaw Battle, the player's Green Imaginite is consumed and the player is loaded into the instance. When the mobs are unfrozen, the server crashes.

Please note that line 9:

[18-12-21 21:09:28] [CppScripts] Attempted to load CppScript for 'scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_MARK.lua', but returned InvalidScript.

was solved by verifying that the /scripts/ai folder was properly copied.

### Reproduction steps

Compile the latest server source to a VS SLN file.
Open the solution and build all projects.
(As of commit 93ddd50, there is a compilation error:
1>F:\Desktop\DarkflameServer-main\dScripts\BuccaneerValiantShip.cpp(15,1): error C3493: 'skill' cannot be implicitly captured because no default capture mode has been specified
1>F:\Desktop\DarkflameServer-main\dScripts\BuccaneerValiantShip.cpp(15,1): error C3493: 'behavior' cannot be implicitly captured because no default capture mode has been specified
1>Done building project "dGame.vcxproj" -- FAILED.
The game executables from this build process were used as they were stable when booted.)

Launch the MasterServer.exe in the Release folder.
Connect to the server from the LU client.
Attempt to enter the Frakjaw Battle minigame.
The server will remove 1 Green Imaginite and create a world instance, and transfer the player to this instance.
From here, the world instance will crash and the player will be locked in the instance until removed to the main menu, where the player will be at the statue outside the Frakjaw Battle minigame. 

### Expected Behavior

The five enemies should be unfrozen from the opening cinematic and the player should be allowed to begin participating in the minigame. 

### Environment

Windows 11 x64

**Comment by piersonjon** [comment]
Cleaning out the solution, excluding the BuccaneerValiantShip.cpp from the solution and removing it from CppScripts.cpp allows the solution to compile into executables, however the issue still occurs. I was able to complete the quest by altering the itemId of one of my items to match the Sword of Fire, however it was not functional as a weapon until it was sold to a vendor and bought back. I suspect that a modified version of the /skip-ags code in the SlashCommands for /skip-nj matching QuestID 1818 may have also been able to solve the quest lock, although that route would not have awarded the Sword of Fire.

**Comment by MickVermeulen** [comment]
Can you try building from the latest source again? The script issue has been fixed there.

**Comment by piersonjon** [comment]
Thank you, the fix issued today solves the compilation error.
I am still experiencing the root issue of the crash in WorldServer when the activity is starter and the first Unstun timer is executed.  
Log file attached:
[WorldServer_2001_5_1639934152.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7741240/WorldServer_2001_5_1639934152.log)
 
Observable behavior: https://youtu.be/WcQ9cEdiO4k

**Comment by kevin-wise** [comment]
I also see the same issue

**Comment by kevin-wise** [comment]
still seeing this issue. Just pulled and rebuilt today. My log file looks nearly identical
[WorldServer_2001_6_1644211661.log](https://github.com/DarkflameUniverse/DarkflameServer/files/8012674/WorldServer_2001_6_1644211661.log)
Any ideas?

**Comment by EmosewaMC** [comment]
Does this issue still happen on the latest commit?

**Comment by EmosewaMC** [comment]
Closing due to inactivity.  If the issue persists please re-open.
