### ISSUE TITLE
Not getting packages in mailbox

### ISSUE THREAD

**Issue by shrill1** [DarkflameUniverse/DarkflameServer#93]
Issue: Not receiving packages in the mail.
Example: The "ninjago item" from the Rocco Sirocco quest in Avant Gardens

**Comment by Lego6245** [comment]
This is likely the same issue that is fixed by following the steps in #46. Follow the steps in that issue + reboot the server, and new characters who go through the quest will get the mail message.

**Comment by MickVermeulen** [comment]
@shrill1 can you confirm you still have this issue after describing the steps above?

**Comment by NealSpellman** [comment]
Closing this given the user hasn't responded after our fix. Open a new issue if this issue still persists after following the above comment's steps.
